Feature/issue history - make retrieval of history dependent on GetHistory argument/parameters switch
AtlassianPS/JiraPS pull request #441
Opened 2021-07-15 19:14 UTC by GeekTieGuy

### Description

Introduce the argument/parameter GetHistory to allow control of fetching issue history at call site

### Motivation and Context

Getting the history is very useful, but it would be even better if it can be a choice at the call site.

### Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### Checklist

- [ ] My code follows the code style of this project.
- [ ] I have added Pester Tests that describe what my changes should do.
- [ ] I have updated the documentation accordingly.

2021-08-31 00:26 UTC, GeekTieGuy commented
Is there any chance this will get picked up? I'm not familiar with the community/process, but I think the change is useful and fairly cleanly implemented.

2023-06-21 15:16 UTC, lipkau requested changes
Sorry that it took me so long to review this PR.

with the new CI setup, you can see which tests are failing.
But I have pointed out the most important things that are missing above.

2023-06-21 15:16 UTC, lipkau commented on JiraPS/Public/Get-JiraStatus.ps1
This file is missing documentation `docs/en-US/commands/Get-JiraStatus.md` and tests `Tests/Functions/Get-JiraStatus.Unit.Tests.ps1`.

2023-06-21 15:16 UTC, lipkau commented on JiraPS/Public/Get-JiraIssue.ps1
`Tests/Functions/Get-JiraIssue.Unit.Tests.ps1` needs to be extended with this new functionality.

2023-06-21 15:16 UTC, lipkau commented on JiraPS/Public/Invoke-JiraMethod.ps1
can you elaborate on why this change is necessary?

2023-06-21 15:16 UTC, lipkau commented on JiraPS/Public/Get-JiraStatus.ps1
> +        $IdOrName,
Please rename variable to `$Status` to be analog to similar implementations.
eg `JiraPS/Public/Get-JiraField.ps1`

The documentations should elaborate on what values are allowed to be used for the parameter.

2023-08-04 23:39 UTC, GeekTieGuy commented on JiraPS/Public/Invoke-JiraMethod.ps1
I don't remember precisely anymore, because it's been a long time since I did this work. I think it had to do with the "toString" identifier colliding with a .NET method, and this was the simplest way I could think of to avoid that collision.

2026-05-07 17:55 UTC, merged