Fix issue with /createmetadata endpoint deprecation
AtlassianPS/JiraPS pull request #489
Opened 2023-11-13 22:56 UTC by claudiospizzi

### Description

Try to fix the issue with `New-JiraIssue` because of the deprecation of the createmeta endpoint: https://confluence.atlassian.com/jiracore/createmeta-rest-endpoint-to-be-removed-975040986.html

Should solve these issues: https://github.com/AtlassianPS/JiraPS/issues/461 https://github.com/AtlassianPS/JiraPS/issues/469

### Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### Checklist

- [x] My code follows the code style of this project.
- [ ] I have added Pester Tests that describe what my changes should do.
- [ ] I have updated the documentation accordingly.

2024-03-28 18:30 UTC, seanportercci commented
Bump! We would really like to see this fix get merged in, our release automation is currently broken due to this change...

2024-03-28 18:52 UTC, ChefkeGremmen commented
And another bump from me as well.

2024-06-11 12:04 UTC, mwallner commented
👀

2024-06-11 18:28 UTC, lipkau reviewed
I haven't looked into the details yet; but maybe someone knows and can save me some time:

* With what Jira versions is this change compatible?
* Is it compatible with Jira Server?
* Is it compatible with Jira Could?

2024-06-13 14:38 UTC, lipkau commented
please rebase your branch on `develop` for the tests to run.
You didn't grant maintainers access to your fork, so I can't do it for you.

2024-06-13 14:40 UTC, lipkau requested changes
please rebase your branch on `develop` for the tests to run.
You didn't grant maintainers access to your fork, so I can't do it for you.

2026-04-24 05:45 UTC, lipkau commented
Thanks @claudiospizzi, and apologies for the long wait. The createmeta endpoint deprecation has been addressed in #583, which paginates the v3 createmeta endpoint. Closing as superseded.

2026-04-24 05:45 UTC, closed without merging